/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef WINFORM_PRIVATE_H
#define WINFORM_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.0.0.0"
#define VER_MAJOR	1
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	0
#define COMPANY_NAME	"zhblue"
#define FILE_VERSION	"1.0.0.0"
#define FILE_DESCRIPTION	"OPL3USB VGM Player"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"OPL3USB VGM Player"
#define PRODUCT_VERSION	"1.0.0.0"

#endif /*WINFORM_PRIVATE_H*/
